[workspace]
resolver = "2"
members = [
  "crates/encore",
  "crates/minipak",
  "crates/pixie",
  "crates/stage1",
  "crates/stage2",
]

[profile.dev]
panic = "abort"

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"
