[package]
name = "encore"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.8.0"
compiler_builtins = "0.1.144"
displaydoc = { version = "0.2.5", default-features = false }
linked_list_allocator = "0.10.5"
rlibc = "1.0.0"
