[package]
name = "stage1"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
compiler_builtins = { version = "0.1.144", features = ["mem"] }
encore = { path = "../encore" }
